### PR TITLE
download all clothes at once without going 1 by 1

### PR DESCRIPTION
**Pull request by SKITTLE6969**

### CODE REVIEW

**Comment by ahcenezdh** [comment]
What is the point to do that?

**Comment by SKITTLE6969** [comment]
> What is the point to do that?
saves alot of time if a new player joins a server and having to go through all the clothing menu categories to download everything

**Comment by SKITTLE6969** [comment]
> What is the point to do that?

saves alot of time if a new player joins a server and having to go through all the clothing menu categories to download everything

**Comment by FjamZoo** [comment]
If your players are having issues loading clothing fast its because those clothing items are extremely unoptimized

**Comment by SKITTLE6969** [comment]
> If your players are having issues loading clothing fast its because those clothing items are extremely unoptimized

it cycles through all the clothing items and queue them to download all together at the same time rather than going through the clothing menu categories one by one :)

**Comment by SKITTLE6969** [comment]
> So where does the command go? So it does it automatictly

/downloadclothes in chat

**Pull request closed without merging**
