### PR TITLE
Add compatibility to QS-INVENTORIE V2

### PR DESCRIPTION
**Pull request by tugapower0**
Setup new settings Config.InventoryQS to true in config.lua if you use Quasar Inventorie V2 with clothing items enabled

### CODE REVIEW

**Comment by tugapower0** [comment]
Also wee need to stop the loop when player its creating the char, or when finished it ends up with every single cloth it see go on inventory when first time spawning on city

**Comment by tugapower0** [comment]
But the startcustomization callback its not handling only stuff that is on the NUI ? We need also to cover ox_lib and ox_target if not mistaken when swaping trough stored outfits.

**Comment by timonation** [comment]
this developer is not interested in any changes or bugfixes. in addition very unfriendly

**Comment by TA-NEON** [comment]
we will be give update as soon as possible.

**Comment by TheiLLeniumStudios** [comment]
Closing as this is not a great solution

**Pull request closed without merging**
