### PR TITLE
feat: initial support for ox_core

### LINKED ISSUE #242: [Enhancement] Add Ox support and Docs to install
Ox-Core is new and upcoming and I am sure people would like to use this for their appearance, I would suggest supporting Ox_core and adding documentation to install it

### PR DESCRIPTION
**Pull request by thelindat**
Technically resolves #242, however ox_core is undergoing a rewrite in TypeScript (so would not work on older versions).

### CODE REVIEW

**Comment by thelindat** [comment]
I'll have more for this in the future but just want to get basic support in for now.

**Comment by TheiLLeniumStudios** [comment]
Can you fix the linting errors please? Everything else looks good @thelindat

**Comment by TheiLLeniumStudios** [comment]
LGTM. Thanks!

**Pull request merged**
